### ISSUE TITLE
У вікні Лікарня при певних значеннях в полі Вулиця при натисканні кнопки Зберегти помилка

### ISSUE THREAD

**Issue by dimapct** [zuuuiko/docnote#11]
1) значення "длаводліво" - немає помилки
2) значення " длаводліво" - немає помилки
3) значення з десяти пробілів - є помилка

**Comment by zuuuiko** [comment]
Довжина строки всіх полів обмежена довжиною поля, що вказана в базі. Для поля Номер телефону (вікно Доктор) реалізовно валідацію (червона рамка, тултіп)
