### ISSUE TITLE
Я, як лікар, хочу мати можливість згенерувати документ 025-6/о (стат талон)

### ISSUE THREAD

**Issue by dimapct** [zuuuiko/docnote#28]

**Comment by dimapct** [comment]
[Стат талон.docx](https://github.com/zuuuiko/docnote/files/368030/default.docx)

**Comment by dimapct** [comment]
[stat talon with tags.docx](https://github.com/zuuuiko/docnote/files/405450/stat.talon.with.tags.docx)

**Comment by zuuuiko** [comment]
[stat.talon.with.tags1.docx](https://github.com/zuuuiko/docnote/files/405674/stat.talon.with.tags1.docx)

**Comment by dimapct** [comment]
Это статистический талон на пациента. Он заполняется при каждом обращении. Там просто

заполняются поля и все.

Паспортные данные можно оставить статичными. Когда мы входим в карточку пациента –

сверху в тех полях-закладках. Еще одна – эта форма.

Когда мы ее открываем – Паспортная часть заполнена. Автоматически. Остальное ставим

Цифры.

Есть Несколько моментов:

Пункт 11: Место обслуживания, Дата, гдесмотрел. Тут какой момент: Я могу дома или в

поликлинике , пока не закрыл этот стат талон Смотреть 20 и 30 раз. И необходимо

предусмотреть, чтобы это можно было внести. (ТАКОЕ КОЛИЧЕСТВО РАЗ). Даты опять же

выпадающим календариком.

Пункт 12. Діагноз заключний –мы прописываем диагноз словами. И далее квадратики там Код

МКБ 10 ( посмотрите: http://mkb-10.com/). Возможно ли как-то сделать так, чтобы код по мкб.

Возможно было сопоставить с диагнозом. Какой ньюанс. Как-то или перенести вручную Эту

кодировку и выбирать из выпадающего списка. Или Например: Мы вбиваем около 20 кодов

МКБ 10. И они автоматически подогнаны под диагноз. И затем выбираем Диагноз

Высвечивается автоматически код. Или Наоборот. Если Появляется новый диагноз – и такого

кода МКБ 10 нет у нас в талоне. Мы добавляем код и диагноз и затем просто , если еще раз

этот диагноз попадается. Его выбираем (он уже забит).

И пункт №17.

Там есть Лікарняний листок: Когда выдан и закрыт

Довідка Когда выдана и закрыта.

Так вот, в форме это не указано, но нам необходимо писать номер Больничного или справки.

Можно ли добавить графы.

Все, что в форме это делается, но если я открываю больничный лист или справку. Я жму рядом

с «Лікарняний листок» или «Довідка» птичку. И автоматически Эти графы становятся

активными и вбиваю туда номер и когда открыт и когда закрыт.

Например: Я больничный не открывал. Ничего не жму. Все так и остается. Открыл: Смотрим

немного выше.

Далее: я эту форму сохраняю. И она у меня как бы в программе висит не закрытая. И каждый

раз, когда я вхожу в пациента она мне как-то о себе должна напоминать, чтобы я вбивал всю

информацию.

Смотрим пункт 19. Случай закончен и не закончен.

Как только я ставлю пункт «Закончен».

Стат Талон Готов. У Него варианта 2. Либо Я его распечатываю и отдаю в стат отдел. Либо

приношу его на флешке.

Поэтому необходима кнопка. Сохранить в архив пациента. Распечатать.

НУ а потом если чего я отправлю по почте.

Но с почтой как поступить. Либо прямо из программы вытянуть, либо епсть возможность

сохранять в папку на компьютер и оттуда вытягивать.

НО НЕОБХОДИМОЕ УСЛОВИЕ. ПОКА Я НЕ ЗАКРЫЛ СТАТ ТАЛОН. КОГДА Я ЗАХОЖУ В КАРТОЧКУ

ПАЦИЕНТА. НЕОБХОДИМО,ЧТОБЫ ОН КАК-ТО ПОДСВЕЧИВАЛ. ИЛИ СРАЗУ В ГЛАЗА

БРОСАЛСЯ!!!!!! ЧТОБЫ Я В СУМАТОХЕ ПРО НЕГО НЕ ЗАБЫЛ!!!!!

ЕЩЕ ОДИН ОЧЕНЬ ВАЖНЫЙ МОМЕНТ. ПАЦИЕНТ ОБРАТИЛСЯ 1 РАЗ, ЧЕРЕЗ 2 ДНЯ ОПЯТЬ. СТАЛО

ЛУЧШЕ. БОЛЬШЕ НЕ ПРИШЕЛ. НО СТАТ ТАЛОН ВИСИТ. ЭТО ОТЧЕТНОСТЬ. ЗА ЭТО РУГАЮТ.

ОБЫЧНО ИДЕТ СОЗВОН С ПАЦИЕНТОМ И ОН ГОВОРИТ: ВСЕ ОТЛИЧНО, Я ЗДОРОВ. ЗНАЧИТ Я

СТАТ ТАЛОН ЗАКРЫВАЮ. СООТВЕТСТВЕННО ОН УХОДИТ В АРХИВ ПАЦИЕНТА. И ЗАКРЫТ И

НИГДЕ НЕ СВЕТИТСЯ И НЕ НАПОМИНАЕТ МНЕ. СЛУЧАЙ ЗАКРЫТ.
